version: "3.9"
services: 
  php: 
    image: php:7.4-fpm 
    volumes: 
      - .:/var/www/html
  mysql:
    image: mysql
    environment: 
      MYSQL_ROOT_PASSWORD: "toor"
    volumes:  
      - base_de_datos:/var/lib/mysql
  nginx: 
    image: nginx  
    ports: 
      - "8000:80"
    volumes: 
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html

volumes: 
  base_de_datos: